/*
  # Create AuraFit AI Core Tables

  1. New Tables
    - `users` - Extended profile data linked to auth.users
      - `id` (uuid, primary key, references auth.users)
      - `email` (text, unique)
      - `full_name` (text)
      - `avatar_url` (text, nullable)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

    - `biometrics` - Scan results and body measurements
      - `id` (uuid, primary key)
      - `user_id` (uuid, foreign key to users)
      - `height` (integer, cm)
      - `body_shape` (enum: hourglass, rectangle, pear, triangle, inverted_triangle, athletic)
      - `skin_tone` (enum: cool, warm, neutral)
      - `color_palette` (jsonb array of hex colors)
      - `scan_date` (timestamp)
      - `measurements` (jsonb with shoulder, waist, hip measurements)

    - `products` - Fashion product catalog
      - `id` (uuid, primary key)
      - `name` (text)
      - `description` (text)
      - `price` (numeric)
      - `category` (text: office, gym, party, casual)
      - `occasion` (text)
      - `image_url` (text, Unsplash links)
      - `sustainable_rating` (integer 1-5)
      - `sizes_available` (text array)
      - `color_palette` (jsonb)
      - `created_at` (timestamp)

    - `recommendations` - AI-generated product matches
      - `id` (uuid, primary key)
      - `user_id` (uuid, foreign key)
      - `product_id` (uuid, foreign key)
      - `match_score` (integer 0-100)
      - `reason` (text)
      - `created_at` (timestamp)

    - `user_wardrobe` - Saved favorite items
      - `id` (uuid, primary key)
      - `user_id` (uuid, foreign key)
      - `product_id` (uuid, foreign key)
      - `added_at` (timestamp)

    - `blog_articles` - Style Guide content
      - `id` (uuid, primary key)
      - `title` (text)
      - `slug` (text, unique)
      - `content` (text)
      - `excerpt` (text)
      - `featured_image_url` (text)
      - `author` (text)
      - `category` (text: color-theory, body-types, sustainability, science)
      - `created_at` (timestamp)
      - `updated_at` (timestamp)

  2. Security
    - Enable RLS on all tables
    - Users can only read/write their own data
    - Products and blog articles are publicly readable
    - Recommendations are read-only for authenticated users (generated by system)

  3. Indexes
    - Foreign key indexes for performance
    - Slug index for blog articles
    - User-based indexes for queries
*/

-- Create enums for body_shape and skin_tone
CREATE TYPE body_shape_enum AS ENUM ('hourglass', 'rectangle', 'pear', 'triangle', 'inverted_triangle', 'athletic');
CREATE TYPE skin_tone_enum AS ENUM ('cool', 'warm', 'neutral');

-- Users table (linked to auth.users)
CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own data"
  ON users FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own data"
  ON users FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Biometrics table
CREATE TABLE IF NOT EXISTS biometrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  height integer,
  body_shape body_shape_enum,
  skin_tone skin_tone_enum,
  color_palette jsonb,
  scan_date timestamptz DEFAULT now(),
  measurements jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_biometrics_user_id ON biometrics(user_id);

ALTER TABLE biometrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own biometrics"
  ON biometrics FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own biometrics"
  ON biometrics FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own biometrics"
  ON biometrics FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Products table (public read)
CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric(10, 2) NOT NULL,
  category text NOT NULL,
  occasion text,
  image_url text,
  sustainable_rating integer DEFAULT 3 CHECK (sustainable_rating >= 1 AND sustainable_rating <= 5),
  sizes_available text[] DEFAULT ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  color_palette jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_occasion ON products(occasion);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are publicly readable"
  ON products FOR SELECT
  TO anon, authenticated
  USING (true);

-- Recommendations table (read-only for users)
CREATE TABLE IF NOT EXISTS recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  match_score integer NOT NULL DEFAULT 0 CHECK (match_score >= 0 AND match_score <= 100),
  reason text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_recommendations_user_id ON recommendations(user_id);
CREATE INDEX idx_recommendations_product_id ON recommendations(product_id);

ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own recommendations"
  ON recommendations FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- User wardrobe table (saved items)
CREATE TABLE IF NOT EXISTS user_wardrobe (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  added_at timestamptz DEFAULT now(),
  UNIQUE(user_id, product_id)
);

CREATE INDEX idx_user_wardrobe_user_id ON user_wardrobe(user_id);

ALTER TABLE user_wardrobe ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own wardrobe"
  ON user_wardrobe FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own wardrobe"
  ON user_wardrobe FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own wardrobe items"
  ON user_wardrobe FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Blog articles table (public read)
CREATE TABLE IF NOT EXISTS blog_articles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text UNIQUE NOT NULL,
  content text NOT NULL,
  excerpt text,
  featured_image_url text,
  author text DEFAULT 'AuraFit AI',
  category text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_blog_articles_slug ON blog_articles(slug);
CREATE INDEX idx_blog_articles_category ON blog_articles(category);

ALTER TABLE blog_articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Blog articles are publicly readable"
  ON blog_articles FOR SELECT
  TO anon, authenticated
  USING (true);